version: "3.7"
services:
  servlet-mongo:
    image: mongo:latest
    container_name: "servlet-mongo"
    ports:
      - 27017:27017
    networks:
      monitoring:
        aliases:
          - servlet-mongo
  servlet-spring-boot-app:
    build: .
    image: master-thesis/servlet
    depends_on:
      - servlet-mongo
    ports:
      - 8080:8080
    links:
      - servlet-mongo
    networks:
      monitoring:
        aliases:
          - servlet-spring-boot-app
      spring-app:
  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  spring-app:
    name: spring-app
  monitoring: