version: "3.7"
services:
  reactive-mongo:
    image: mongo:latest
    container_name: "reactive-mongo"
    ports:
      - 27019:27017
    networks:
      monitoring:
        aliases:
          - reactive-mongo
  reactive-spring-boot-app:
    build: .
    image: master-thesis/reactive
    depends_on:
      - reactive-mongo
    ports:
      - 8070:8080
    links:
      - reactive-mongo
    networks:
      monitoring:
        aliases:
          - reactive-spring-boot-app
  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring: