scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'reactive-spring-boot-app'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reactive-spring-boot-app:8070']
  - job_name: 'grafana'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']